import { test, expect } from '@playwright/test'

async function clearStorage(page) {
  await page.goto('/')
  await page.evaluate(async () => {
    localStorage.clear()
    // links live in IndexedDB (localStorage is only the v1 recovery source);
    // without this, a "clear" silently keeps the previous data
    const dbs = await (indexedDB.databases ? indexedDB.databases() : Promise.resolve([]))
    await Promise.all(dbs.map((d) => new Promise((resolve) => {
      const req = indexedDB.deleteDatabase(d.name)
      req.onsuccess = req.onerror = req.onblocked = () => resolve()
    })))
  })
  await page.reload()
}

async function ensureSaveFormOpen(page, { more = false } = {}) {
  const urlInput = page.locator('#save-url')
  if (!(await urlInput.isVisible().catch(() => false))) {
    await page.getByRole('button', { name: 'Save a link', exact: true }).click()
  }
  if (more) {
    const moreBtn = page.getByRole('button', { name: 'More options', exact: true })
    if ((await moreBtn.getAttribute('aria-expanded')) !== 'true') await moreBtn.click()
  }
}

async function saveLink(page, { url, title, description, image, tags, category, important, mustHave }) {
  const needsMore = description !== undefined || image !== undefined || tags !== undefined || important || mustHave
  await ensureSaveFormOpen(page, { more: needsMore })
  await page.locator('#save-url').fill(url)
  if (title !== undefined) await page.locator('#save-title').fill(title)
  if (description !== undefined) await page.locator('#save-desc').fill(description)
  if (image !== undefined) await page.locator('#save-image').fill(image)
  if (tags !== undefined) await page.locator('#save-tags').fill(tags)
  if (category) await page.locator('#save-category').selectOption(category)
  if (important) await page.getByLabel('Important').check()
  if (mustHave) await page.getByLabel('Must Have').check()
  await page.getByRole('button', { name: 'Save link' }).click()
  await expect(page.getByText('Link saved')).toBeVisible({ timeout: 3000 }).catch(() => {})
}

async function installBackupCapture(page) {
  // Capture the actual Blob a real export produces, without relying on the
  // unreliable `download` event for blob URLs. Patching URL.createObjectURL
  // is test-only browser setup and does not touch the application code.
  await page.addInitScript(() => {
    window.__capturedBackups = []
    const originalCreateObjectURL = URL.createObjectURL.bind(URL)
    URL.createObjectURL = function (obj, ...args) {
      const url = originalCreateObjectURL(obj, ...args)
      try {
        if (obj instanceof Blob) {
          obj.text()
            .then((text) => window.__capturedBackups.push({ text, url }))
            .catch(() => {})
        }
      } catch {
        /* ignore */
      }
      return url
    }
  })
}

// Click the real "Export Backup" button and return the actual JSON payload
// generated by the export implementation.
async function clickExportAndCaptureBackup(page) {
  const before = await page.evaluate(() => window.__capturedBackups.length)
  await page.getByRole('button', { name: 'Export Backup' }).click()
  await page.waitForFunction((b) => window.__capturedBackups.length > b, before, { timeout: 5000 })
  return page.evaluate((b) => JSON.parse(window.__capturedBackups[b].text), before)
}

test.describe('Backup E2E', () => {
  test.beforeEach(async ({ page }) => {
    await installBackupCapture(page)
    await clearStorage(page)
  })

  test('1. Export Backup', async ({ page }) => {
    test.setTimeout(60000)
    await page.goto('/')
    // local profile: Account menu -> Edit local profile -> Local Profile panel
    await page.locator('.identity-btn').click()
    await page.getByRole('button', { name: 'Edit local profile' }).click()
    await page.locator('#lp-name').fill('Backup Tester')
    await page.locator('#lp-bio').fill('Local-first profile bio')
    await page.getByRole('button', { name: 'Save changes' }).click()
    // reload: dismisses the (still-open) Account panel and verifies the local
    // profile name AND bio persisted to storage
    await page.reload()
    await expect(page.getByText('Backup Tester')).toBeVisible()
    // Bio is inside the AccountPanel dialog — open it to verify persistence
    await page.locator('.identity-btn').click()
    await expect(page.getByText('Local-first profile bio')).toBeVisible()
    // Close AccountPanel before continuing with link operations
    await page.keyboard.press('Escape')

    // link with all flags
    await saveLink(page, {
      url: 'https://example.com/export-test',
      title: 'Export Title',
      description: 'Export Desc',
      image: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0iI2NjYyIvPjwvc3ZnPg==',
      tags: 'backup, test',
      category: 'GitHub',
      important: true,
      mustHave: true,
    })
    const card = page.locator('article.card').first()
    await card.getByRole('button', { name: 'Toggle Favorite' }).click()
    await expect(card.getByRole('button', { name: 'Toggle Favorite' })).toHaveAttribute('aria-pressed', 'true')

    // export using the real export button and capture the generated JSON
    const json = await clickExportAndCaptureBackup(page)

    expect(json.app).toBe('Save_Link')
    expect(json.version).toBe(2)
    expect(json.exportedAt).toBeDefined()
    expect(() => new Date(json.exportedAt).toISOString()).not.toThrow()
    expect(json.profile.name).toBe('Backup Tester')
    expect(json.profile.bio).toBe('Local-first profile bio')
    expect(Array.isArray(json.links)).toBe(true)
    expect(Array.isArray(json.folders)).toBe(true)
    expect(json.settings).toBeDefined()
    expect(json.settings.appearance).toBeDefined()
    expect(json.settings.colorScheme).toBeDefined()
    const exported = json.links.find((l) => l.title === 'Export Title')
    expect(exported).toBeDefined()
    expect(exported.originalUrl).toBe('https://example.com/export-test')
    expect(exported.normalizedUrl).toBe('https://example.com/export-test')
    expect(exported.url).toBe('https://example.com/export-test')
    expect(exported.important).toBe(true)
    expect(exported.mustHave).toBe(true)
    expect(exported.favorite).toBe(true)
    expect(exported.category).toBe('GitHub')
    expect(exported.tags).toEqual(expect.arrayContaining(['backup', 'test']))
    expect(exported.description).toBe('Export Desc')

    await expect(page.getByText('Backup exported')).toBeVisible()
    await expect(page.getByText(/Last backup:/)).toBeVisible()
  })

  test('2. Export uses current in-memory data', async ({ page }) => {
    test.setTimeout(60000)
    await page.goto('/')
    await saveLink(page, { url: 'https://example.com/in-memory', title: 'InMemory Title' })
    await expect(page.locator('article.card').first()).toContainText('InMemory Title')

    // Tamper localStorage to different data, without affecting in-memory
    await page.evaluate(() => {
      localStorage.setItem('save_link:links', JSON.stringify([{ id: 'old', url: 'https://old.com', title: 'Old' }]))
    })

    const json = await clickExportAndCaptureBackup(page)
    // exported should reflect displayed InMemory Title, not old.com
    expect(json.links.some((l) => l.title === 'InMemory Title')).toBe(true)
    expect(json.links.some((l) => l.title === 'Old')).toBe(false)
  })

  test('3. Import valid backup merges data', async ({ page }) => {
    await page.goto('/')
    await saveLink(page, { url: 'https://example.com/existing', title: 'Existing' })
    await expect(page.locator('article.card')).toHaveCount(1)

    const backup = {
      app: 'Save_Link',
      version: 1,
      exportedAt: new Date().toISOString(),
      profile: { name: 'Imported User', bio: 'Imported Bio' },
      links: [
        {
          id: 'imported1',
          originalUrl: 'https://example.com/imported1',
          normalizedUrl: 'https://example.com/imported1',
          url: 'https://example.com/imported1',
          title: 'Imported Title 1',
          description: 'Imported Desc',
          image: '',
          tags: ['imported'],
          category: 'Reddit',
          important: true,
          mustHave: false,
          favorite: true,
          domain: 'example.com',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'imported2',
          originalUrl: 'example.com/imported2',
          normalizedUrl: 'https://example.com/imported2',
          url: 'https://example.com/imported2',
          title: 'Imported Title 2',
          description: '',
          image: '',
          tags: [],
          category: 'Other',
          important: false,
          mustHave: true,
          favorite: false,
          domain: 'example.com',
          createdAt: new Date().toISOString(),
        },
      ],
    }

    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'backup.json',
      mimeType: 'application/json',
      buffer: Buffer.from(JSON.stringify(backup)),
    })
    // No URL overlap with the local link -> no duplicate => no preview modal;
    // the import is additive and runs immediately.
    await expect(page.getByText(/Import complete/)).toBeVisible()
    await expect(page.locator('article.card')).toHaveCount(3)
    await expect(page.getByText('Existing', { exact: true })).toBeVisible()
    await expect(page.getByText('Imported Title 1', { exact: true })).toBeVisible()
    await expect(page.getByText('Imported Title 2', { exact: true })).toBeVisible()
    await expect(page.locator('.stat-card', { hasText: 'Total saved' }).locator('.num')).toHaveText('3')
    await expect(page.locator('.stat-card', { hasText: 'Favorites' }).locator('.num')).toHaveText('1')
    await expect(page.locator('.stat-card', { hasText: 'Must Have' }).locator('.num')).toHaveText('1')
    await expect(page.locator('.stat-card', { hasText: 'Important' }).locator('.num')).toHaveText('1')
    // flags survive the import
    const imp1 = page.locator('article.card', { hasText: 'Imported Title 1' })
    await expect(imp1.getByRole('button', { name: 'Toggle Favorite' })).toHaveAttribute('aria-pressed', 'true')
    await expect(imp1.getByRole('button', { name: 'Toggle Important' })).toHaveAttribute('aria-pressed', 'true')
  })

  test('4. Import cancel keeps existing data', async ({ page }) => {
    await page.goto('/')
    await saveLink(page, { url: 'https://example.com/keep', title: 'Keep Me' })
    await expect(page.locator('article.card')).toHaveCount(1)

    // A duplicate URL triggers the merge-preview modal; Cancel must keep
    // everything unchanged.
    const backup = {
      app: 'Save_Link',
      version: 2,
      exportedAt: new Date().toISOString(),
      profile: { name: 'New' },
      links: [{
        id: 'dup', originalUrl: 'https://example.com/keep', normalizedUrl: 'https://example.com/keep', url: 'https://example.com/keep', title: 'Keep Me (backup)', description: '', image: '', tags: [], category: 'Other', important: false, mustHave: false, favorite: false, domain: 'example.com', createdAt: new Date().toISOString(),
      }],
      folders: [],
    }

    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'backup.json',
      mimeType: 'application/json',
      buffer: Buffer.from(JSON.stringify(backup)),
    })
    const importDialog = page.getByRole('dialog')
    await expect(importDialog).toBeVisible()
    await importDialog.getByRole('button', { name: 'Cancel' }).click()

    await expect(page.locator('article.card').first()).toContainText('Keep Me')
    await expect(page.locator('article.card')).toHaveCount(1)
    await expect(page.getByText('Keep Me (backup)')).toHaveCount(0)
    // no success toast for import
    await expect(page.getByText(/Import complete/)).toHaveCount(0)
  })

  test('5. Invalid JSON', async ({ page }) => {
    await page.goto('/')
    await saveLink(page, { url: 'https://example.com/keep2', title: 'Keep2' })
    await expect(page.locator('article.card')).toHaveCount(1)

    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'bad.json',
      mimeType: 'application/json',
      buffer: Buffer.from('not json {'),
    })

    await expect(page.locator('.toast')).toContainText('Invalid backup file: not valid JSON')
    await expect(page.locator('article.card')).toHaveCount(1)
    await expect(page.locator('article.card').first()).toContainText('Keep2')
  })

  test('6. Wrong app identifier', async ({ page }) => {
    await page.goto('/')
    await saveLink(page, { url: 'https://example.com/keep3', title: 'Keep3' })

    const bad = { app: 'OtherApp', version: 1, exportedAt: new Date().toISOString(), profile: {}, links: [] }
    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'bad.json',
      mimeType: 'application/json',
      buffer: Buffer.from(JSON.stringify(bad)),
    })

    await expect(page.locator('.toast')).toContainText('Invalid backup: wrong app identifier')
    await expect(page.locator('article.card')).toHaveCount(1)
  })

  test('7. Unsupported version', async ({ page }) => {
    await page.goto('/')
    await saveLink(page, { url: 'https://example.com/keep4', title: 'Keep4' })

    const bad = { app: 'Save_Link', version: 999, exportedAt: new Date().toISOString(), profile: {}, links: [] }
    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'bad.json',
      mimeType: 'application/json',
      buffer: Buffer.from(JSON.stringify(bad)),
    })

    await expect(page.locator('.toast')).toContainText('Unsupported backup version')
    await expect(page.locator('article.card')).toHaveCount(1)
  })

  test('8. Invalid links field — missing and not array', async ({ page }) => {
    await page.goto('/')
    await saveLink(page, { url: 'https://example.com/keep5', title: 'Keep5' })

    const missing = { app: 'Save_Link', version: 1, exportedAt: new Date().toISOString(), profile: {} }
    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'bad.json',
      mimeType: 'application/json',
      buffer: Buffer.from(JSON.stringify(missing)),
    })
    await expect(page.locator('.toast')).toContainText('Invalid backup: missing links')
    await expect(page.locator('article.card')).toHaveCount(1)

    const notArray = { app: 'Save_Link', version: 1, exportedAt: new Date().toISOString(), profile: {}, links: 'not-array' }
    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'bad2.json',
      mimeType: 'application/json',
      buffer: Buffer.from(JSON.stringify(notArray)),
    })
    await expect(page.locator('.toast')).toContainText('Invalid backup: links must be an array')
    await expect(page.locator('article.card')).toHaveCount(1)
  })

  test('9. Malformed records', async ({ page }) => {
    await page.goto('/')
    const backup = {
      app: 'Save_Link',
      version: 1,
      exportedAt: new Date().toISOString(),
      profile: {},
      links: [
        null,
        'string',
        123,
        { id: 'bad1' },
        { id: 'bad2', url: '' },
        { id: 'good', originalUrl: 'https://example.com/good', normalizedUrl: 'https://example.com/good', url: 'https://example.com/good', title: 'Good Link', description: '', image: '', tags: ['a'], category: 'Other', important: false, mustHave: false, favorite: false, domain: 'example.com', createdAt: new Date().toISOString() },
      ],
    }

    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'backup.json',
      mimeType: 'application/json',
      buffer: Buffer.from(JSON.stringify(backup)),
    })
    // The malformed records are dropped during normalization. No duplicates in
    // an empty store -> no preview modal, import runs immediately.
    await expect(page.getByText(/Import complete/)).toBeVisible()
    await expect(page.locator('article.card')).toHaveCount(1)
    await expect(page.locator('article.card').first()).toContainText('Good Link')
    // ensure app didn't crash
    await expect(page.getByText('Save Links', { exact: false }).first()).toBeVisible()
  })

  test('10. Persistence after import', async ({ page }) => {
    await page.goto('/')
    const backup = {
      app: 'Save_Link',
      version: 1,
      exportedAt: new Date().toISOString(),
      profile: { name: 'Persist User', bio: 'Persist Bio' },
      links: [
        {
          id: 'persist1',
          originalUrl: 'https://example.com/persist1',
          normalizedUrl: 'https://example.com/persist1',
          url: 'https://example.com/persist1',
          title: 'Persist Link',
          description: '',
          image: '',
          tags: [],
          category: 'GitHub',
          important: true,
          mustHave: true,
          favorite: true,
          domain: 'example.com',
          createdAt: new Date().toISOString(),
        },
      ],
    }

    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'backup.json',
      mimeType: 'application/json',
      buffer: Buffer.from(JSON.stringify(backup)),
    })
    // empty store -> no duplicates -> immediate import, no preview modal
    await expect(page.getByText(/Import complete/)).toBeVisible()
    await expect(page.locator('article.card').first()).toContainText('Persist Link')

    await page.reload()
    await expect(page.locator('article.card').first()).toContainText('Persist Link')
    // local-first invariant: the backup's profile is deliberately NOT imported;
    // the on-device identity is untouched.
    await expect(page.locator('.identity-name')).toContainText('Local User')
    await expect(page.getByText('Persist User')).toHaveCount(0)
    await expect(page.locator('article.card').first().getByRole('button', { name: 'Toggle Favorite' })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.locator('article.card').first().getByRole('button', { name: 'Toggle Important' })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.locator('.stat-card', { hasText: 'Favorites' }).locator('.num')).toHaveText('1')
  })

  test('11. Last backup', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByText('Last backup:')).toHaveCount(0)
    await saveLink(page, { url: 'https://example.com/last', title: 'Last Test' })

    const json1 = await clickExportAndCaptureBackup(page)
    expect(json1.links.some((l) => l.title === 'Last Test')).toBe(true)

    await expect(page.getByText(/Last backup:/)).toBeVisible()
    const text1 = await page.getByText(/Last backup:/).textContent()
    expect(text1).toContain('Last backup:')

    // second export should update timestamp
    await page.waitForTimeout(1100)
    const json2 = await clickExportAndCaptureBackup(page)
    expect(json2.links.some((l) => l.title === 'Last Test')).toBe(true)
    const text2 = await page.getByText(/Last backup:/).textContent()
    expect(text2).toContain('Last backup:')
    // texts should be different or at least still visible
    await expect(page.getByText(/Last backup:/)).toBeVisible()
  })

  test('12. Security — arbitrary fields not executed', async ({ page }) => {
    await page.goto('/')
    const backup = {
      app: 'Save_Link',
      version: 1,
      exportedAt: new Date().toISOString(),
      profile: {},
      links: [
        {
          id: 'sec1',
          originalUrl: 'https://example.com/secure',
          normalizedUrl: 'https://example.com/secure',
          url: 'https://example.com/secure',
          title: '<img src=x onerror=alert(1)>',
          description: '<script>alert(1)</script>',
          image: '',
          tags: [],
          category: 'Other',
          important: false,
          mustHave: false,
          favorite: false,
          domain: 'example.com',
          createdAt: new Date().toISOString(),
          malicious: '<script>alert(1)</script>',
          __proto__: { polluted: true },
        },
      ],
    }

    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'backup.json',
      mimeType: 'application/json',
      buffer: Buffer.from(JSON.stringify(backup)),
    })
    // empty store -> no duplicates -> immediate import (XSS payload NOT run)
    await expect(page.getByText(/Import complete/)).toBeVisible()
    const card = page.locator('article.card').first()
    // title should be rendered as text, not HTML
    await expect(card.getByText('<img src=x onerror=alert(1)>')).toBeVisible()
    // no script element should be rendered inside card
    await expect(card.locator('script')).toHaveCount(0)
    // ensure no img with onerror executed - check that card does not contain executed script
    await expect(card).toContainText('<script>alert(1)</script>')
    await expect(card.locator('script')).toHaveCount(0)
    // ensure __proto__ pollution didn't happen - check window polluted not exists
    const polluted = await page.evaluate(() => ({}).polluted)
    expect(polluted).toBeUndefined()
  })

  // Regression: the real Import button in the new merge-preview modal must
  // actually run the import, close the dialog, and show a summary. This
  // exercises the full DataBackup -> App.vue event boundary, NOT just
  // mergeImportData(). Guards against the "mergeLinks is not defined" failure
  // where the click threw and left the modal stuck open.
  test('13. Import button (Keep existing) performs merge, closes dialog, shows summary', async ({ page }) => {
    test.setTimeout(60000)
    await page.goto('/')
    await saveLink(page, { url: 'https://example.com/existing', title: 'Existing' })
    await expect(page.locator('article.card')).toHaveCount(1)

    const backup = {
      app: 'Save_Link', version: 2, exportedAt: new Date().toISOString(), profile: { name: 'Imported' },
      links: [
        { id: 'dup1', originalUrl: 'https://example.com/existing', normalizedUrl: 'https://example.com/existing', url: 'https://example.com/existing', title: 'Existing (backup)', description: '', image: '', tags: [], category: 'Other', important: false, mustHave: false, favorite: false, domain: 'example.com', createdAt: new Date().toISOString() },
        { id: 'new1', originalUrl: 'https://example.com/new1', normalizedUrl: 'https://example.com/new1', url: 'https://example.com/new1', title: 'New One', description: '', image: '', tags: [], category: 'Other', important: false, mustHave: false, favorite: false, domain: 'example.com', createdAt: new Date().toISOString() },
      ],
      folders: [],
    }
    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(backup)),
    })
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    // Keep existing = skip (default radio)
    await dialog.getByRole('button', { name: 'Import', exact: true }).click()
    // dialog closes
    await expect(dialog).toHaveCount(0)
    // summary appears
    await expect(page.getByText(/Import complete/)).toBeVisible()
    // new item added, existing preserved (no duplicate card)
    await expect(page.locator('article.card')).toHaveCount(2)
    await expect(page.getByText('New One')).toBeVisible()
    await expect(page.getByText('Existing', { exact: true })).toBeVisible()
    await expect(page.getByText('Existing (backup)')).toHaveCount(0)
  })

  test('14. Import button (Replace existing) performs merge, closes dialog, shows summary', async ({ page }) => {
    test.setTimeout(60000)
    await page.goto('/')
    await saveLink(page, { url: 'https://example.com/existing', title: 'Existing Local' })
    await expect(page.locator('article.card')).toHaveCount(1)

    const backup = {
      app: 'Save_Link', version: 2, exportedAt: new Date().toISOString(), profile: { name: 'Imported' },
      links: [
        { id: 'dup1', originalUrl: 'https://example.com/existing', normalizedUrl: 'https://example.com/existing', url: 'https://example.com/existing', title: 'Existing REPLACED', description: '', image: '', tags: [], category: 'Other', important: false, mustHave: false, favorite: false, domain: 'example.com', createdAt: new Date().toISOString() },
        { id: 'new1', originalUrl: 'https://example.com/new1', normalizedUrl: 'https://example.com/new1', url: 'https://example.com/new1', title: 'New One', description: '', image: '', tags: [], category: 'Other', important: false, mustHave: false, favorite: false, domain: 'example.com', createdAt: new Date().toISOString() },
      ],
      folders: [],
    }
    await page.locator('.backup-card input[type="file"]').setInputFiles({
      name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(backup)),
    })
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    // choose Replace
    await dialog.locator('input[name="import-strategy"][value="replace"]').check()
    await dialog.getByRole('button', { name: 'Import', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await expect(page.getByText(/replaced/)).toBeVisible()
    await expect(page.locator('article.card')).toHaveCount(2)
    await expect(page.getByText('Existing REPLACED')).toBeVisible()
    await expect(page.getByText('Existing Local')).toHaveCount(0)
    await expect(page.getByText('New One')).toBeVisible()
  })
})
